---
abstract: 'MapReduce is a simple Map-Reduce platform that uses Perl 5 and Redis.'
author:
  - 'James Barton <james@revolet.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MapReduce
no_index:
  directory:
    - inc
    - t
requires:
  Moo: 0
  Redis::hiredis: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.11
